server:
  port: 10080

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:17001/eureka #单机版
      defaultZone: http://eureka7001.com:17001/eureka,http://eureka7002.com:17002/eureka  #集群版

  instance:
    instance-id: order10080
    prefer-ip-address: true  #访问路径可以显示IP地址

